version: !!str 3
services:
  authz:
    build: .
    image: authz:1
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:8080
  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
